### ISSUE TITLE
Create one step process for converting usgs time series data to CF-1.6

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/usgs-cmg-portal#32] opened 2014-11-25 22:52 UTC
@kwilcox had been working with the files from 
http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/CF-1.6/catalog.html
for his portal work, but these files in this directory came from the "raw" files in this directory:
http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/catalog.html
converted using this script:
http://nbviewer.ipython.org/bc431264273be627a4f5

After discussion today, we decided a better approach would be for @kwilcox to process the files directly from the "raw"  directory and simply take some of the metadata and other code as needed from the above script.  This way @emontgomery-usgs will be able to add new files to the `geoport:/data2/emontgomery/stellwagen/Data` directory and have them show up in the portal.

And we will have a one step process to convert "raw" data to CF-1.6 compliant data instead of a two-step process.

**Comment by rsignell-usgs** [comment] 2015-01-10 00:01
We finally ran this and we were somewhat surprised by the result.  I tried running:
```
 python collect.py --download --output=./tmp --projects EUROSTRATAFORM
```
and this turned these 4 datasets:
```
7011adc-a.nc  7021mc-a.nc  7031adc-a.nc  7032mc-a.nc
```
into 21 directories each with 1 file:
```
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_702:sea_water_practical_salinity/S_40_2002-11-08T12:50Z_TO_2003-02-16T13:02Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:sea_water_temperature/Tx_1211_2002-11-08T08:47Z_TO_2003-02-16T15:47Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:sea_surface_height/hght_18_2002-11-08T08:47Z_TO_2003-02-16T15:47Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:upward_sea_water_velocity/w_1204_2002-11-08T08:47Z_TO_2003-02-16T15:47Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_702:sea_water_pressure/P_1_2002-11-08T12:50Z_TO_2003-02-16T13:02Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_702:air_temperature/T_20_2002-11-08T12:50Z_TO_2003-02-16T13:02Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_702:sea_water_sigma_theta/STH_71_2002-11-08T12:50Z_TO_2003-02-16T13:02Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:sea_water_electrical_conductivity/C_51_2002-11-08T08:37Z_TO_2003-02-16T14:36Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:direction_of_sea_water_velocity/dir_310_2002-11-08T08:47Z_TO_2003-02-16T15:47Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:air_temperature/T_20_2002-11-08T08:37Z_TO_2003-02-16T14:36Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_701:sea_water_pressure/P_4_2002-11-08T13:17Z_TO_2003-02-14T03:32Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:sea_water_speed/spd_300_2002-11-08T08:47Z_TO_2003-02-16T15:47Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_701:sea_water_speed/spd_300_2002-11-08T13:17Z_TO_2003-02-14T03:32Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_701:sea_water_temperature/Tx_1211_2002-11-08T13:17Z_TO_2003-02-14T03:32Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_701:upward_sea_water_velocity/w_1204_2002-11-08T13:17Z_TO_2003-02-14T03:32Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_701:direction_of_sea_water_velocity/dir_310_2002-11-08T13:17Z_TO_2003-02-14T03:32Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:sea_water_practical_salinity/S_40_2002-11-08T08:37Z_TO_2003-02-16T14:36Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_702:sea_water_electrical_conductivity/C_51_2002-11-08T12:50Z_TO_2003-02-16T13:02Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:sea_water_sigma_theta/STH_71_2002-11-08T08:37Z_TO_2003-02-16T14:36Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_701:sea_surface_height/hght_18_2002-11-08T13:17Z_TO_2003-02-14T03:32Z.nc
./urn:ioos:sensor:gov.usgs.cmgp:eurostrataform_703:sea_water_pressure/P_4_2002-11-08T08:47Z_TO_2003-02-16T15:47Z.nc
```
I gather this is a form convenient for the Axiom stack, but how hard would it be to use this code to  write CF-1.6 versions of our existing files?

**Comment by rsignell-usgs** [comment] 2015-01-13 18:06
@kwilcox , would it be hard to create use your work here to create python code to do a one-to-one conversion of our netcdf files into CF-1.6 compliant netcdf files?

**Comment by kwilcox** [comment] 2015-01-20 18:16
@rsignell-usgs @emontgomery-usgs I've made the changes so you can generate the CF1.6 files.  See the README for an additional command line argument "cf16.  You should be able to do this now:

`python collect.py --download --projects EUROSTRATAFORM --output=./tmp cf16`

**Comment by rsignell-usgs** [comment] 2015-01-20 18:53
It first failed because `epic2py` was not installed.   
After `epic2py` installation, I'm getting:
```
rsignell@gam:/usgs/data2/emontgomery/stellwagen/usgs-cmg-portal/woods_hole_obs_data$ python collect.py --download --projects EUROSTRATAFORM --output=./tmp cf16
2015-01-20 13:52:32 gam root[28344] INFO {'EUROSTRATAFORM': {'catalog_xml': 'http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM/catalog.xml', 'project_summary': 'The EuroSTRATAFORM Po and Apennine Sediment Transport and Accumulation (PASTA) experiment was an international study of sediment-transport processes and formation of geological strata in the Adriatic Sea.', 'project_name': 'EUROSTRATAFORM', 'project_title': 'EuroSTRATAFORM', 'contributor_name': 'C. Sherwood'}}
2015-01-20 13:52:32 gam thredds_crawler[28344] INFO Crawling: http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM/catalog.xml
2015-01-20 13:52:33 gam root[28344] INFO Found 4 datasets in EUROSTRATAFORM!
2015-01-20 13:52:33 gam root[28344] INFO Found 4 TOTAL datasets!
2015-01-20 13:52:33 gam root[28344] INFO Downloading http://geoport.whoi.edu/thredds/fileServer/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM/7011adc-a.nc
Traceback (most recent call last):
  File "collect.py", line 858, in <module>
    main(args.output, args.download, args.format, projects, os.path.realpath(args.csv_metadata_file))
  File "collect.py", line 406, in main
    downloaded_files = download(download_folder, project_metadata)
  File "collect.py", line 232, in download
    logger.info("{!s} saved ({!s}/{!s})".format(num + 1, len(total_datasets)))
IndexError: tuple index out of range

```

**Comment by kwilcox** [comment] 2015-01-20 20:52
ugh.  I committed a few lines I shouldn't have... one sec.

**Comment by kwilcox** [comment] 2015-01-20 21:37
@rsignell-usgs pull and give it another shot

**Comment by rsignell-usgs** [comment] 2015-01-20 21:47
@kwilcox ,   now working!    Awesome!
Just one more little thing:  it seems a bit silly to download the data since we are running this script on the machine where the data is local.    I was thinking of just omitting the `--download` option, and writing a script that softlinks the input directory to `./download` but perhaps it would be easy to allow this option in the code?

If this is hard, don't bother.   It's not that big a deal downloading the data even if it's local.

**Comment by kwilcox** [comment] 2015-01-21 15:16
@rsignell-usgs Just pushed a new command line option `--folder` that allows you to specify the folder to download files into.  If you use this option and omit the `--download` option, it will scan the folder for the files to translate.  See `README.md` for more details!

**Closed by kwilcox** 2015-01-21 15:16 UTC

**Comment by rsignell-usgs** [comment] 2015-01-21 15:29
Must have the syntax a bit wrong?
Does it matter if there are = or not after the parameters?

```
 $ls /usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM
7011adc-a.nc  7021mc-a.nc  7031adc-a.nc  7032mc-a.nc


$ python collect.py
--folder=/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM
--projects=EUROSTRATAFORM --output=./tmp2 cf16

rsignell@gam:/usgs/data2/emontgomery/stellwagen/usgs-cmg-portal/woods_hole_obs_data$
python collect.py
--folder=/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM
--projects=EUROSTRATAFORM --output=./tmp2 cf16
Traceback (most recent call last):
  File "collect.py", line 858, in <module>
    main(args.output, args.folder, args.download, args.format, projects,
os.path.realpath(args.csv_metadata_file))
  File "collect.py", line 422, in main
    project_name, _ = tmpnc.id.split("/")
  File "netCDF4.pyx", line 1939, in netCDF4.Dataset.__getattr__
(netCDF4.c:24474)
  File "netCDF4.pyx", line 1884, in netCDF4.Dataset.getncattr
(netCDF4.c:23689)
  File "netCDF4.pyx", line 937, in netCDF4._get_att (netCDF4.c:14866)
AttributeError: NetCDF: Attribute not found
```

On Wed, Jan 21, 2015 at 10:16 AM, Kyle Wilcox <notifications@github.com>
wrote:

> Closed #32
> <https://github.com/axiom-data-science/usgs-cmg-portal/issues/32>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/axiom-data-science/usgs-cmg-portal/issues/32#event-222370752>
> .
>



-- 
Dr. Richard P. Signell   (508) 457-2229
USGS, 384 Woods Hole Rd.
Woods Hole, MA 02543-1598

**Comment by rsignell-usgs** [comment] 2015-01-21 15:31
Seems like I have the syntax a bit wrong?
Does it matter if there are `=` in the specification of input parameters?
```
 $ls /usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM
7011adc-a.nc  7021mc-a.nc  7031adc-a.nc  7032mc-a.nc


$ python collect.py --folder=/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM --projects=EUROSTRATAFORM --output=./tmp2 cf16

rsignell@gam:/usgs/data2/emontgomery/stellwagen/usgs-cmg-portal/woods_hole_obs_data$ python collect.py --folder=/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM --projects=EUROSTRATAFORM --output=./tmp2 cf16
Traceback (most recent call last):
  File "collect.py", line 858, in <module>
    main(args.output, args.folder, args.download, args.format, projects, os.path.realpath(args.csv_metadata_file))
  File "collect.py", line 422, in main
    project_name, _ = tmpnc.id.split("/")
  File "netCDF4.pyx", line 1939, in netCDF4.Dataset.__getattr__ (netCDF4.c:24474)
  File "netCDF4.pyx", line 1884, in netCDF4.Dataset.getncattr (netCDF4.c:23689)
  File "netCDF4.pyx", line 937, in netCDF4._get_att (netCDF4.c:14866)
AttributeError: NetCDF: Attribute not found
```

**Comment by kwilcox** [comment] 2015-01-21 16:43
I don't have a way to test this on your machine, all I have access to are the files through THREDDS.  It is working as intended for me:

```
(usgs_cmg)kwilcox@terrapin:~/Development/usgs-cmg-portal/woods_hole_obs_data (master)$ python collect.py --download --folder=/tmp/euro --projects=EUROSTRATAFORM --output=./tmp2 cf16
2015-01-21 11:42:57 terrapin thredds_crawler[20285] INFO Crawling: http://geoport.whoi.edu/thredds/catalog/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM/catalog.xml
2015-01-21 11:42:58 terrapin root[20285] INFO Found 4 datasets in EUROSTRATAFORM!
2015-01-21 11:42:58 terrapin root[20285] INFO Found 4 TOTAL datasets!
2015-01-21 11:42:58 terrapin root[20285] INFO Downloading http://geoport.whoi.edu/thredds/fileServer/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM/7011adc-a.nc
2015-01-21 11:42:59 terrapin root[20285] INFO 7011adc-a.nc saved (1/4)
2015-01-21 11:42:59 terrapin root[20285] INFO Downloading http://geoport.whoi.edu/thredds/fileServer/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM/7021mc-a.nc
2015-01-21 11:43:01 terrapin root[20285] INFO 7021mc-a.nc saved (2/4)
2015-01-21 11:43:01 terrapin root[20285] INFO Downloading http://geoport.whoi.edu/thredds/fileServer/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM/7031adc-a.nc
2015-01-21 11:43:03 terrapin root[20285] INFO 7031adc-a.nc saved (3/4)
2015-01-21 11:43:03 terrapin root[20285] INFO Downloading http://geoport.whoi.edu/thredds/fileServer/usgs/data2/emontgomery/stellwagen/Data/EUROSTRATAFORM/7032mc-a.nc
2015-01-21 11:43:04 terrapin root[20285] INFO 7032mc-a.nc saved (4/4)
2015-01-21 11:43:04 terrapin root[20285] INFO FILE: /tmp/euro/7011adc-a.nc
2015-01-21 11:43:04 terrapin root[20285] INFO Copying u_1205 into u_1205
2015-01-21 11:43:04 terrapin root[20285] INFO Copying v_1206 into v_1206
2015-01-21 11:43:04 terrapin root[20285] INFO Copying w_1204 into w_1204
2015-01-21 11:43:04 terrapin root[20285] INFO Copying Werr_1201 into Werr_1201
2015-01-21 11:43:04 terrapin root[20285] INFO Copying AGC_1202 into AGC_1202
2015-01-21 11:43:04 terrapin root[20285] INFO Copying PGd_1203 into PGd_1203
2015-01-21 11:43:04 terrapin root[20285] INFO Copying hght_18 into hght_18
2015-01-21 11:43:04 terrapin root[20285] INFO Copying Tx_1211 into Tx_1211
2015-01-21 11:43:04 terrapin root[20285] INFO Copying P_4 into P_4
2015-01-21 11:43:04 terrapin root[20285] INFO Copying time
2015-01-21 11:43:06 terrapin root[20285] INFO FILE: /tmp/euro/7021mc-a.nc
2015-01-21 11:43:06 terrapin root[20285] INFO Copying T_20 into T_20
2015-01-21 11:43:06 terrapin root[20285] INFO Copying C_51 into C_51
2015-01-21 11:43:06 terrapin root[20285] INFO Copying P_1 into P_1
2015-01-21 11:43:06 terrapin root[20285] INFO Copying S_40 into S_40
2015-01-21 11:43:06 terrapin root[20285] INFO Copying STH_71 into STH_71
2015-01-21 11:43:06 terrapin root[20285] INFO Copying time
2015-01-21 11:43:06 terrapin root[20285] INFO FILE: /tmp/euro/7031adc-a.nc
2015-01-21 11:43:06 terrapin root[20285] INFO Copying u_1205 into u_1205
2015-01-21 11:43:06 terrapin root[20285] INFO Copying v_1206 into v_1206
2015-01-21 11:43:06 terrapin root[20285] INFO Copying w_1204 into w_1204
2015-01-21 11:43:06 terrapin root[20285] INFO Copying Werr_1201 into Werr_1201
2015-01-21 11:43:07 terrapin root[20285] INFO Copying AGC_1202 into AGC_1202
2015-01-21 11:43:07 terrapin root[20285] INFO Copying PGd_1203 into PGd_1203
2015-01-21 11:43:07 terrapin root[20285] INFO Copying hght_18 into hght_18
2015-01-21 11:43:07 terrapin root[20285] INFO Copying Tx_1211 into Tx_1211
2015-01-21 11:43:07 terrapin root[20285] INFO Copying P_4 into P_4
2015-01-21 11:43:07 terrapin root[20285] INFO Copying time
2015-01-21 11:43:08 terrapin root[20285] INFO FILE: /tmp/euro/7032mc-a.nc
2015-01-21 11:43:08 terrapin root[20285] INFO Copying T_20 into T_20
2015-01-21 11:43:08 terrapin root[20285] INFO Copying C_51 into C_51
2015-01-21 11:43:08 terrapin root[20285] INFO Copying S_40 into S_40
2015-01-21 11:43:08 terrapin root[20285] INFO Copying STH_71 into STH_71
2015-01-21 11:43:08 terrapin root[20285] INFO Copying time
(usgs_cmg)kwilcox@terrapin:~/Development/usgs-cmg-portal/woods_hole_obs_data (master)$ python collect.py --folder=/tmp/euro --projects=EUROSTRATAFORM --output=./tmp2 cf16
2015-01-21 11:43:13 terrapin root[20328] INFO FILE: /tmp/euro/7032mc-a.nc
2015-01-21 11:43:13 terrapin root[20328] INFO Copying T_20 into T_20
2015-01-21 11:43:13 terrapin root[20328] INFO Copying C_51 into C_51
2015-01-21 11:43:13 terrapin root[20328] INFO Copying S_40 into S_40
2015-01-21 11:43:13 terrapin root[20328] INFO Copying STH_71 into STH_71
2015-01-21 11:43:14 terrapin root[20328] INFO Copying time
2015-01-21 11:43:14 terrapin root[20328] INFO FILE: /tmp/euro/7011adc-a.nc
2015-01-21 11:43:14 terrapin root[20328] INFO Copying u_1205 into u_1205
2015-01-21 11:43:14 terrapin root[20328] INFO Copying v_1206 into v_1206
2015-01-21 11:43:14 terrapin root[20328] INFO Copying w_1204 into w_1204
2015-01-21 11:43:14 terrapin root[20328] INFO Copying Werr_1201 into Werr_1201
2015-01-21 11:43:14 terrapin root[20328] INFO Copying AGC_1202 into AGC_1202
2015-01-21 11:43:14 terrapin root[20328] INFO Copying PGd_1203 into PGd_1203
2015-01-21 11:43:14 terrapin root[20328] INFO Copying hght_18 into hght_18
2015-01-21 11:43:14 terrapin root[20328] INFO Copying Tx_1211 into Tx_1211
2015-01-21 11:43:14 terrapin root[20328] INFO Copying P_4 into P_4
2015-01-21 11:43:14 terrapin root[20328] INFO Copying time
2015-01-21 11:43:15 terrapin root[20328] INFO FILE: /tmp/euro/7021mc-a.nc
2015-01-21 11:43:15 terrapin root[20328] INFO Copying T_20 into T_20
2015-01-21 11:43:15 terrapin root[20328] INFO Copying C_51 into C_51
2015-01-21 11:43:15 terrapin root[20328] INFO Copying P_1 into P_1
2015-01-21 11:43:15 terrapin root[20328] INFO Copying S_40 into S_40
2015-01-21 11:43:15 terrapin root[20328] INFO Copying STH_71 into STH_71
2015-01-21 11:43:15 terrapin root[20328] INFO Copying time
2015-01-21 11:43:16 terrapin root[20328] INFO FILE: /tmp/euro/7031adc-a.nc
2015-01-21 11:43:16 terrapin root[20328] INFO Copying u_1205 into u_1205
2015-01-21 11:43:16 terrapin root[20328] INFO Copying v_1206 into v_1206
2015-01-21 11:43:16 terrapin root[20328] INFO Copying w_1204 into w_1204
2015-01-21 11:43:16 terrapin root[20328] INFO Copying Werr_1201 into Werr_1201
2015-01-21 11:43:16 terrapin root[20328] INFO Copying AGC_1202 into AGC_1202
2015-01-21 11:43:16 terrapin root[20328] INFO Copying PGd_1203 into PGd_1203
2015-01-21 11:43:16 terrapin root[20328] INFO Copying hght_18 into hght_18
2015-01-21 11:43:16 terrapin root[20328] INFO Copying Tx_1211 into Tx_1211
2015-01-21 11:43:16 terrapin root[20328] INFO Copying P_4 into P_4
2015-01-21 11:43:16 terrapin root[20328] INFO Copying time
```

**Comment by rsignell-usgs** [comment] 2015-01-23 16:35
I gchatted with @kwilcox yesterday, and we figured out that to use local files instead of downloading, he needs to identify an experiment with a set of files, so we left it as it for the time being.  The download doesn't take long compared to the conversion anyway.   So I wrote a small bash script to convert our files:
```
cd /usgs/data2/emontgomery/stellwagen/usgs-cmg-portal/woods_hole_obs_data
more do_convert.sh
```
```bash
#!/bin/bash
for proj in /usgs/data2/emontgomery/stellwagen/Data/*
do
   project=`echo $proj | sed -e 's;/usgs/data2/emontgomery/stellwagen/Data/;;'`
   echo $project
   python collect.py --download --projects $project --output=/usgs/data2/emontgo
mery/stellwagen/cf16 cf16
done
```

**Comment by daf** [comment] 2015-01-23 16:40
Rich, use `basename` for this kind of substitution. (and its cousin, `dirname` if needed)

... this episode of bikeshedding with Dave brought to you by the letter P and the number 9.

**Comment by rsignell-usgs** [comment] 2015-01-23 17:03
@daf:  okay you popped your head up on this.  What's your better version of this script?

**Comment by rsignell-usgs** [comment] 2015-01-23 17:17
@daf, is this it?:
```bash
#!/bin/bash
for proj in /usgs/data2/emontgomery/stellwagen/Data/*
do
   project=$(basename "$proj")
   echo $project
   python collect.py --download --projects $project \
        --output=/usgs/data2/emontgomery/stellwagen/cf16 cf16
done
```

**Comment by daf** [comment] 2015-01-23 18:12
That's what I meant, it's more succinct.  (i realize I'm being entirely unhelpful here, hence the joke about bikeshedding)

**Comment by kwilcox** [comment] 2015-01-23 18:17
Can you just leave off the --projects option and do them all?

**Comment by emontgomery-usgs** [comment] 2015-04-06 13:14
folks-

I've been through this thread and thought that I should be able to modify
then run Rich's do_convert.sh, and It would download the (FI14 in this
case) data then convert the files and put the output in the CF-1.6
directory.

I have /home/usgs/anaconda/bin in my path, but get a missing epic2cf when I
try to run the script.

$ sh do_convert.sh
FI14
Traceback (most recent call last):
  File "collect.py", line 13, in <module>
    import epic2cf
ImportError: No module named epic2cf

What might I be missing in my path?

Thanks! Ellyn

On Fri, Jan 23, 2015 at 1:17 PM, Kyle Wilcox <notifications@github.com>
wrote:

> Can you just leave off the --projects option and do them all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/axiom-data-science/usgs-cmg-portal/issues/32#issuecomment-71237876>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356
